/**
 * Copyright (C) 2011 rwoo@gmx.de
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.googlecode.catchexception.internal;

/**
 * Marks a proxy as generated by {@link SubclassProxyFactory}.
 * This is useful for testing.
 * <p>
 * EXAMPLE:
 * <code><pre class="prettyprint lang-java">assert new SubclassProxyFactory(...).createProxy(obj) instanceof SubclassProxy;
 * </pre></code>
 * 
 * @author rwoo
 */
public interface SubclassProxy {
    // empty by purpose
}
