package com.googlecode.catchexception.internal;

/**
 * Marks a proxy as generated by {@link MockitoCglibJmockObjenesisProxyFactory}.
 * This is useful for testing.
 * <p>
 * EXAMPLE:
 * <code><pre>assert new MockitoCglibJmockObjenesisProxyFactory(...).createProxy(obj) instanceof CglibProxy;
 * </pre></code>
 * 
 * @author rwoo
 */
public interface CglibProxy {
    // empty by purpose
}
