package com.googlecode.catchexception.internal;

/**
 * Marks a proxy as generated by {@link InterfaceOnlyProxyFactory}. This is useful for
 * testing.
 * <p>
 * EXAMPLE:
 * <code><pre>assert new InterfaceOnlyProxyFactory(...).createProxy(obj) instanceof InterfaceOnlyProxy;
 * </pre></code>
 * 
 * @author rwoo
 */
public interface InterfaceOnlyProxy {
    // empty by purpose
}
