package com.googlecode.catchexception.internal;

/**
 * Marks a proxy as generated by {@link SubclassProxyFactory}.
 * This is useful for testing.
 * <p>
 * EXAMPLE:
 * <code><pre class="prettyprint lang-java">assert new SubclassProxyFactory(...).createProxy(obj) instanceof SubclassProxy;
 * </pre></code>
 * 
 * @author rwoo
 */
public interface SubclassProxy {
    // empty by purpose
}
